server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
          - Path=/ecommerce/**
          filters:
          - AuthenticationFilter
          
        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
          - Path=/ecommerce/**
          filters:
          - AuthenticationFilter
          

          
  application:
    name: API-GATEWAY 
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 