spring:
 cloud:
   gateway:
     routes:
       - id: main-app
         uri: lb://MAIN-APP
         predicates:
           - Path=/app/**
         filters:
           - AuthenticationFilter


       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: user-auth-service
         uri: lb://USER-AUTH-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: API-GATEWAY

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka