server:
  port: 8082
  
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  #User for get the configuration from the configuration server 
  config:
      import: optional:configserver:http://localhost:8085/
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka 
      
      
#Okta Spring Security Configuration
okta:
  oauth2:
    issuer: https://dev-11076645.okta.com/oauth2/default
    audience: api://default
    